### ISSUE TITLE
مستندات آموزشی برای dagger

### ISSUE THREAD

**Issue by pishguy** [mmirhoseini/fyber_mobile_offers#1]
سلام دوست عزیز. برای این dagger و rxjava 
اگه به فارسی بتونید آموزش یا توضیحات مفیدی بدید ممنون میشم. پیاده سازی اجرا و لزوم استفاده از اون
منظورم هستش. به انگلیسی خیلی مطالعه کردم ولی فک میکنم درست مفهومش رو نگرفتم

**Comment by mohsenoid** [comment]
مهدی جان
حقیقتا توضیح کل پروژه خیلی برام مقدور نیست. اگر بخش خاصی مد نظرتون هست بهم بگین تا براتون اون موضوع خاص رو کامل توضیح بدم.

**Comment by pishguy** [comment]
ممنونم شما لطف میکنید دوست عزیز منت میزارید.
راستش الان در مورد پیاده سازی این
Dagger
برام نا مفهوم هستش. در مورد اینجکشن اطلاعاتی دارم و تو پی اچ پی استفاده کردم ولی تو جاوا تو نحوه پیاده سازیش به صورت مفهمومی به مشکل خوردم. درست نمیفهمم کلاسهایی که مینویسه اعم از
provider
و یا
singletone 
چی هستش ممنون میشم این موارد رو توضیح بدید دوست عزیز

**Comment by mohsenoid** [comment]
موضوع اینجاست که واقعا پیچیده است و شخصا ۳ روز طول کشید تا فقط با مفاهیمش آشنا شدم!
من توضیحات کلی میدم و خودتون باید با خوندن کدهای مختلف و استفاده ازش در پروژه هاتون بهش مسلط بشین.
مهمتر از اون پیدا کردن دید Dependency Injection هست.

**Comment by mohsenoid** [comment]
بخشهای مختلف پروژه رو باید به component های مختلف بشکنین.

هر بخش یه سری نیازها به کلاسهای مختلف داره، اونها رو از طریق module ها provide میکنین.

کلاسهایی که مشترک کاربرد دارند رو میتونین توی یه component قرار بدین و بقیه رو بصورت subcomponent هایی از اون ایجاد کنین. که با این اوصاف بجای متد inject از plus استفاده میکنیم و عمل inject رو در subcomponent انجام میدیم.

میتونیم برای هر provider بسته به نیاز scope تعریف کنین که نشون دهنده محدوده ایه که اون کلاس باید ساخته و زنده بمونه.

عملا همه دستورات new حذف میشه و بصورت مجتمع توسط dagger انجام میشه.

**Comment by pishguy** [comment]
خیلی عالی. من میتونم ایمیل شما رو داشته باشم؟ اینجا نوشتن فارسی انگلیسی سخته. ممنون میشم

**Comment by mohsenoid** [comment]
mohsen@mirhoseini.com
